Legacy DKMS support for Hardy.

diff --git a/debian/igotu-dkms.postinst b/debian/igotu-dkms.postinst
--- a/debian/igotu-dkms.postinst
+++ b/debian/igotu-dkms.postinst
@@ -33,13 +33,39 @@ case "$1" in
                                 $POSTINST $NAME $CVERSION /usr/share/$PACKAGE_NAME $ARCH $2
                                 exit $?
                         fi
-                        echo "WARNING: $POSTINST does not exist."
                 done
-                echo "ERROR: DKMS version is too old and $PACKAGE_NAME was not"
-                echo "built with legacy DKMS support."
-                echo "You must either rebuild $PACKAGE_NAME with legacy postinst"
-                echo "support or upgrade DKMS to a more current version."
-                exit 1
+
+                # Legacy DKMS support
+                echo "Removing all [$NAME-$CVERSION] DKMS Modules"
+                dkms remove -m $NAME -v $CVERSION --all >/dev/null 2>&1 || true
+                echo "Done."
+                echo "Adding [$NAME-$CVERSION] Module to DKMS build system"
+                dkms add -m $NAME -v $CVERSION >/dev/null
+                if ! dpkg --status linux-headers-`uname -r` 2>/dev/null | grep -qs "Status: install ok installed"; then
+                        flavor=`uname -r | sed "s/.*-//"`
+                        echo
+                        echo "*************************************************"
+                        echo "ERROR: Missing kernel headers."
+                        echo
+                        echo "You appear to have at least some kernel headers"
+                        echo "installed, but you do not have the necessary"
+                        echo "headers to build $PACKAGE_NAME against this kernel."
+                        echo
+                        echo "You might try installing the meta package:"
+                        echo " $ sudo apt-get install linux-headers-$flavor"
+                        echo "or specifically"
+                        echo " $ sudo apt-get install linux-headers-"`uname -r`
+                        echo "to obtain the necessary build dependencies."
+                        echo
+                        echo "*************************************************"
+                        echo
+                        exit 1
+                fi
+                echo "Doing initial module build"
+                dkms build -m $NAME -v $CVERSION >/dev/null
+                echo "Installing initial module"
+                dkms install -m $NAME -v $CVERSION >/dev/null
+                echo "Done."
         ;;
 
         abort-upgrade|abort-remove|abort-deconfigure)
